# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://suneel123.github.io/
baseurl: 
title: Suneel Dondapati
name: Suneel Dondapati
author: Suneel Dondapati
description: Personal blog and resume
website: Suneel23.github.io
website_full: https://Suneel123.github.io/
avatar: profile.png
email: dsuneel1@gmail.com
email_full: mailto:dsuneel@gmail.com
github: Suneel123/Suneel123.github.io # username
twitter: SuneelChowda
linkedin: suneel-dondapati-54161980
stackoverflow: users/7276694/suneel-d  #e.g: users/2735833/proton1h1
researchgate: Suneel_Dondapati3
tel: +91 9491993516
tel_full: tel:+919491993516
google_maps: 'https://goo.gl/maps/S4x6s6kSYGJ2'
address: 6-1173/A, Kodada Road
address1: Near Bank Of India
city: Jaggayyapet
postcode: 521175
country: India
#Comment out if you don't want disqus 
disqus: suneeld
google_analytics: UA-88757760-1


# needed for travis-ci build
exclude: [vendor]
